apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  labels:
    app.kubernetes.io/name: clickhouse
data:
  metrika.xml: |-
    <yandex>
       <zookeeper-servers>
            <node index="1">
                <host>Placeholder_zk1_node</host>
                <port>2181</port>
            </node>
            <node index="2">
                <host>Placeholder_zk2_node</host>
                <port>2181</port>
            </node>
            <node index="3">
                <host>Placeholder_zk3_node</host>
                <port>2181</port>
            </node>
        </zookeeper-servers>

        <clickhouse_remote_servers>
            <cluster_4shards_2replicas>
                <shard>
                    <internal_replication>true</internal_replication>
                    <replica>
                        <host>Placeholder_clickhouse1_node</host>
                        <port>9000</port>
                    </replica>
                    <replica>
                        <host>Placeholder_clickhouse2_node</host>
                        <port>9000</port>
                    </replica>
                </shard>
                <shard>
                    <replica>
                        <internal_replication>true</internal_replication>
                        <host>Placeholder_clickhouse2_node</host>
                        <port>9000</port>
                    </replica>
                    <replica>
                        <host>Placeholder_clickhouse3_node</host>
                        <port>9000</port>
                    </replica>
                </shard>
                <shard>
                    <internal_replication>true</internal_replication>
                    <replica>
                        <host>Placeholder_clickhouse3_node</host>
                        <port>9000</port>
                    </replica>
                    <replica>
                        <host>Placeholder_clickhouse4_node</host>
                        <port>9000</port>
                    </replica>
                </shard>
                <shard>
                    <internal_replication>true</internal_replication>
                    <replica>
                        <host>Placeholder_clickhouse4_node</host>
                        <port>9000</port>
                    </replica>
                    <replica>
                        <host>Placeholder_clickhouse1_node</host>
                        <port>9000</port>
                    </replica>
                </shard>
            </cluster_4shards_2replicas>
        </clickhouse_remote_servers>
    </yandex>
  config.xml: |-
    <?xml version="1.0"?>
    <yandex>
        <logger>
            <level>trace</level>
            <log>/var/log/clickhouse-server/clickhouse-server.log</log>
            <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
            <size>1000M</size>
            <count>10</count>
        </logger>
        <send_crash_reports>
            <enabled>false</enabled>
            <anonymize>false</anonymize>
            <endpoint>https://6f33034cfe684dd7a3ab9875e57b1c8d@o388870.ingest.sentry.io/5226277</endpoint>
        </send_crash_reports>

        <!--display_name>production</display_name--> <!-- It is the name that will be shown in the client -->
        <http_port>8123</http_port>
        <tcp_port>9000</tcp_port>
        <mysql_port>9004</mysql_port>
        <include_from>/etc/clickhouse-server/metrika.xml</include_from>
        <openSSL>
            <server>
                <!-- openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt -->
                <certificateFile>/etc/clickhouse-server/server.crt</certificateFile>
                <privateKeyFile>/etc/clickhouse-server/server.key</privateKeyFile>
                <!-- openssl dhparam -out /etc/clickhouse-server/dhparam.pem 4096 -->
                <dhParamsFile>/etc/clickhouse-server/dhparam.pem</dhParamsFile>
                <verificationMode>none</verificationMode>
                <loadDefaultCAFile>true</loadDefaultCAFile>
                <cacheSessions>true</cacheSessions>
                <disableProtocols>sslv2,sslv3</disableProtocols>
                <preferServerCiphers>true</preferServerCiphers>
            </server>

            <client>
                <loadDefaultCAFile>true</loadDefaultCAFile>
                <cacheSessions>true</cacheSessions>
                <disableProtocols>sslv2,sslv3</disableProtocols>
                <preferServerCiphers>true</preferServerCiphers>
                <!-- Use for self-signed: <verificationMode>none</verificationMode> -->
                <invalidCertificateHandler>
                    <!-- Use for self-signed: <name>AcceptCertificateHandler</name> -->
                    <name>RejectCertificateHandler</name>
                </invalidCertificateHandler>
            </client>
        </openSSL>

        <interserver_http_port>9009</interserver_http_port>
        <listen_host>0.0.0.0</listen_host>
        <max_connections>4096</max_connections>
        <keep_alive_timeout>3</keep_alive_timeout>
        <max_concurrent_queries>100</max_concurrent_queries>
        <max_server_memory_usage>0</max_server_memory_usage>
        <max_thread_pool_size>10000</max_thread_pool_size>
        <max_server_memory_usage_to_ram_ratio>0.9</max_server_memory_usage_to_ram_ratio>
        <total_memory_profiler_step>4194304</total_memory_profiler_step>
        <total_memory_tracker_sample_probability>0</total_memory_tracker_sample_probability>
        <uncompressed_cache_size>8589934592</uncompressed_cache_size>
        <mark_cache_size>5368709120</mark_cache_size>
        <path>/var/lib/clickhouse/</path>
        <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
        <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
        <access_control_path>/var/lib/clickhouse/access/</access_control_path>
        <users_config>users.xml</users_config>
        <default_profile>default</default_profile>
        <custom_settings_prefixes></custom_settings_prefixes>
        <default_database>default</default_database>
        <timezone>Asia/Shanghai</timezone>
        <umask>022</umask>
        <mlock_executable>true</mlock_executable>

        <remote_servers incl="clickhouse_remote_servers" >    </remote_servers>

        <!-- The list of hosts allowed to use in URL-related storage engines and table functions.
            If this section is not present in configuration, all hosts are allowed.
        -->
        <remote_url_allow_hosts>    </remote_url_allow_hosts>

        <zookeeper incl="zookeeper-servers" optional="true" />
        <macros incl="macros" optional="true" />

        <builtin_dictionaries_reload_interval>3600</builtin_dictionaries_reload_interval>
        <!-- Maximum session timeout, in seconds. Default: 3600. -->
        <max_session_timeout>3600</max_session_timeout>
        <!-- Default session timeout, in seconds. Default: 60. -->
        <default_session_timeout>60</default_session_timeout>
        <!-- Query log. Used only for queries with setting log_queries = 1. -->
        <query_log>
            <database>system</database>
            <table>query_log</table>
            <partition_by>toYYYYMM(event_date)</partition_by>
            <!-- Interval of flushing data. -->
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        </query_log>
        <trace_log>
            <database>system</database>
            <table>trace_log</table>
            <partition_by>toYYYYMM(event_date)</partition_by>
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        </trace_log>

        <query_thread_log>
            <database>system</database>
            <table>query_thread_log</table>
            <partition_by>toYYYYMM(event_date)</partition_by>
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        </query_thread_log>

        <metric_log>
            <database>system</database>
            <table>metric_log</table>
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
            <collect_interval_milliseconds>1000</collect_interval_milliseconds>
        </metric_log>

        <asynchronous_metric_log>
            <database>system</database>
            <table>asynchronous_metric_log</table>
            <flush_interval_milliseconds>60000</flush_interval_milliseconds>
        </asynchronous_metric_log>

        <crash_log>
            <database>system</database>
            <table>crash_log</table>
            <partition_by />
            <flush_interval_milliseconds>1000</flush_interval_milliseconds>
        </crash_log>

        <dictionaries_config>*_dictionary.xml</dictionaries_config>

        <compression incl="clickhouse_compression">
            <case>
                <min_part_size>10000000000</min_part_size>
                <min_part_size_ratio>0.01</min_part_size_ratio>
                <method>lz4</method>
            </case>
        </compression>
        <distributed_ddl>
            <path>/clickhouse/task_queue/ddl</path>
        </distributed_ddl>

        <graphite_rollup_example>
            <pattern>
                <regexp>click_cost</regexp>
                <function>any</function>
                <retention>
                    <age>0</age>
                    <precision>3600</precision>
                </retention>
                <retention>
                    <age>86400</age>
                    <precision>60</precision>
                </retention>
            </pattern>
            <default>
                <function>max</function>
                <retention>
                    <age>0</age>
                    <precision>60</precision>
                </retention>
                <retention>
                    <age>3600</age>
                    <precision>300</precision>
                </retention>
                <retention>
                    <age>86400</age>
                    <precision>3600</precision>
                </retention>
            </default>
        </graphite_rollup_example>
        <format_schema_path>/var/lib/clickhouse/format_schemas/</format_schema_path>
    </yandex>
