apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-historyserver
  labels:
    app.kubernetes.io/name: spark-historyserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-historyserver
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark-historyserver
    spec:
      initContainers:
        - name: spark-logs
          image: Placeholder_registry/bigdata:v0.1
          imagePullPolicy: Always
          command:
            - "sh"
            - "-c"
            - "hadoop fs -ls /spark-logs;if [ $? -ne 0 ];then hadoop fs -mkdir /spark-logs && echo 'Created /spark-logs';fi"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
      containers:
        - name: spark-historyserver
          image: Placeholder_registry/bigdata:v0.1
          imagePullPolicy: Always
          resources:
          command:
            - "sh"
            - "-c"
            - "$SPARK_HOME/sbin/start-history-server.sh && tail -f $SPARK_HOME/logs/*"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
              subPath: yarn-site.xml
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/mapred-site.xml
              subPath: mapred-site.xml
            - name: hive-config
              mountPath: /opt/spark/conf/hive-site.xml
              subPath: hive-site.xml
            - name: spark-config
              mountPath: /opt/spark/conf/spark-defaults.conf
              subPath: spark-defaults.conf
          lifecycle:
            preStop:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - "$SPARK_HOME/sbin/stop-history-server.sh"
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: hadoop-config
          configMap:
            name: hadoop-config
        - name: hive-config
          configMap:
            name: hive-config
        - name: spark-config
          configMap:
            name: spark-config
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        shs: "true"
      tolerations:
        - key: "project"
          value: "gdbdc"
          operator: "Equal"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-historyserver
  labels:
    app.kubernetes.io/name: spark-historyserver
spec:
  selector:
    app.kubernetes.io/name: spark-historyserver
  ports:
  - port: 18080
    targetPort: 18080
