apiVersion: apps/v1
kind: Deployment
metadata:
  name: journalnode
  labels:
    app.kubernetes.io/name: journalnode
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: journalnode
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: journalnode
    spec:
      containers:
        - name: journalnode
          image: Placeholder_registry/bigdata-allinnoe:v0.3
          imagePullPolicy: Always
          resources:
          env:
            - name: HADOOP_SSH_OPTS
              value: "-o StrictHostKeyChecking=no -o ConnectTimeout=10s -p 9431"
            - name: LD_LIBRARY_PATH
              value: "/opt/hadoop/lib/native"
            - name: HADOOP_COMMON_LIB_NATIVE_DIR
              value: "/opt/hadoop/lib/native"
          command:
            - "sh"
            - "-c"
            - "hdfs --daemon start journalnode && tail -f /opt/hadoop/logs/*"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: dfs
              mountPath: /dfs
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
              subPath: yarn-site.xml
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/mapred-site.xml
              subPath: mapred-site.xml
          lifecycle:
            preStop:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - "hdfs --daemon stop journalnode"
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: dfs
          hostPath:
            path: /data/dfs
        - name: hadoop-config
          configMap:
            name: hadoop-config
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        jn: "true"
      tolerations:
        - key: "project"
          value: "gdbdc"
          operator: "Equal"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: journalnode
              topologyKey: kubernetes.io/hostname
