apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodemanager
  labels:
    app.kubernetes.io/name: nodemanager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nodemanager
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nodemanager
    spec:
      containers:
        - name: nodemanager
          image: Placeholder_registry/bigdata:v0.1
          imagePullPolicy: Always
          resources:
          env:
            - name: HADOOP_SSH_OPTS
              value: "-o StrictHostKeyChecking=no -o ConnectTimeout=10s -p 9431"
            - name: LD_LIBRARY_PATH
              value: "/opt/hadoop/lib/native"
            - name: HADOOP_COMMON_LIB_NATIVE_DIR
              value: "/opt/hadoop/lib/native"
          command:
            - "sh"
            - "-c"
            - "yarn --daemon start nodemanager && tail -f /opt/hadoop/logs/*"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
              subPath: yarn-site.xml
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/mapred-site.xml
              subPath: mapred-site.xml
            - mountPath: /qcerrdata
              name: qcerr
          lifecycle:
            preStop:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - "yarn --daemon stop nodemanager"
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: hadoop-config
          configMap:
            name: hadoop-config
        - name: qcerr
          persistentVolumeClaim:
            claimName: qcerrdata
      restartPolicy: Always
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        nm: "true"
      tolerations:
        - key: "project"
          value: "gdbdc"
          operator: "Equal"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: nodemanager
              topologyKey: kubernetes.io/hostname
