apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-config
  labels:
    app.kubernetes.io/name: trino
data:
  coordinator.config.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8082
    query.max-memory=8GB
    query.max-memory-per-node=1GB
    discovery.uri=http://Placeholder_trino_master_node:8082
  worker.config.properties: |-
    coordinator=false
    http-server.http.port=8082
    query.max-memory=8GB
    query.max-memory-per-node=1GB
    discovery.uri=http://Placeholder_trino_master_node:8082
  delta.properties: |-
    connector.name=delta-lake
    hive.metastore.uri=thrift://Placeholder_hive_node:9083
    hive.config.resources=/etc/hadoop/core-site.xml,/etc/hadoop/hdfs-site.xml
  hive.properties: |-
    connector.name=hive
    hive.metastore.uri=thrift://Placeholder_hive_node:9083
    hive.config.resources=/etc/hadoop/core-site.xml,/etc/hadoop/hdfs-site.xml
  jmx.properties: |-
    connector.name=jmx
  jvm.config: |-
    -server
    -Xmx16G
    -XX:-UseBiasedLocking
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+ExitOnOutOfMemoryError
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:-OmitStackTraceInFastThrow
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
    -XX:+UnlockDiagnosticVMOptions
    -XX:+UseAESCTRIntrinsics
  log.properties: |-
    io.trino=INFO

