apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-mysql
  labels:
    app.kubernetes.io/name: hive-mysql
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hive-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hive-mysql
    spec:
      containers:
        - name: hive-mysql
          image: Placeholder_registry/mysql:8.0.29
          imagePullPolicy: IfNotPresent
          resources:
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Placeholder_root_password
            - name: MYSQL_USER
              value: hive
            - name: MYSQL_PASSWORD
              value: Placeholder_hive_password
            - name: MYSQL_DATABASE
              value: hive
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --default_authentication_plugin=mysql_native_password
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: data
          hostPath:
            path: /data/mysql-hive
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        hive: "true"
      tolerations:
        - key: "project"
          value: "gdbdc"
          operator: "Equal"
          effect: "NoSchedule"
--- 
apiVersion: v1
kind: Service
metadata:
  name: hive-mysql
  labels:
    app.kubernetes.io/name: hive-mysql
spec:
  selector:
    app.kubernetes.io/name: hive-mysql
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
