apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-config
  labels:
    app.kubernetes.io/name: hive
data:
  hive-site.xml: |-
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
        <property>
            <name>javax.jdo.option.ConnectionUserName</name>
            <value>hive</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionPassword</name>
            <value>Placeholder_hive_password</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionURL</name>
            <value>jdbc:mysql://Placeholder_hive_node:3306/hive?createDatabaseIfNotExist=true&amp;useSSL=false&amp;allowPublicKeyRetrieval=true</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionDriverName</name>
            <value>com.mysql.cj.jdbc.Driver</value>
        </property>
        <property>
            <name>hive.cli.print.current.db</name>
            <value>true</value>
        </property>
        <property>
            <name>hive.cli.print.header</name>
            <value>true</value>
        </property>
        <property>
            <name>hive.metastore.uris</name>
            <value>thrift://Placeholder_hive_node:9083</value>
        </property>
        <property>
            <name>hive.exec.scratchdir</name>
            <value>/user/hive/tmp</value>
        </property>
        <property>
            <name>hive.metastore.warehouse.dir</name>
            <value>/user/hive/warehouse</value>
        </property>
        <property>
            <name>hive.querylog.location</name>
            <value>/tmp/hive/querylog</value>
        </property>
        <property>
            <name>hive.server2.webui.port</name>
            <value>10002</value>
        </property>
        <property>
            <name>hive.server2.thrift.port</name>
            <value>10000</value>
        </property>
        <property>
            <name>hive.merge.mapfiles</name>
            <value>true</value>
        </property>
        <property>
            <name>hive.merge.mapredfiles</name>
            <value>true</value>
        </property>
        <property>
            <name>hive.merge.sparkfiles</name>
            <value>true</value>
        </property>
        <property>
            <name>hive.merge.tezfiles</name>
            <value>true</value>
        </property>
    </configuration>
  spark-defaults.conf: |-
    spark.eventLog.enabled            true
    spark.eventLog.dir                hdfs://Placeholder_nn1_node:8020/sparklogs
    spark.eventLog.compress           true
    spark.serializer                  org.apache.spark.serializer.KryoSerializer
    spark.master                      yarn
    spark.driver.cores                1
    spark.driver.memory               2g
    spark.executor.cores              1
    spark.executor.memory             2g
    spark.executor.instances          1
    spark.sql.warehouse.dir           hdfs://Placeholder_nn1_node:8020/user/hive/warehouse
    spark.yarn.historyServer.address  Placeholder_spark_history_node:18080
    spark.history.ui.port             18080
    spark.history.fs.logDirectory     hdfs://Placeholder_nn1_node:8020/sparklogs
    spark.yarn.jars                   hdfs://Placeholder_nn1_node:8020/sparkjars/*.jar
