apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiveserver2-spark
  labels:
    app: hiveserver2-spark
spec:
  selector:
    matchLabels:
      app: hiveserver2-spark
  replicas: 1
  template:
    metadata:
      labels:
        app: hiveserver2-spark
    spec:
      containers:
        - name: hiveserver2-spark
          image: harbor.gistack.cn/bigdata/hive-on-spark:v1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
          command:
            - "sh"
            - "-c"
            - "hive --service hiveserver2"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: hive-on-spark
              mountPath: /opt/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: hive-on-spark
              mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: hive-on-spark
              mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
              subPath: yarn-site.xml
            - name: hive-on-spark
              mountPath: /opt/hadoop/etc/hadoop/mapred-site.xml
              subPath: mapred-site.xml
            - name: hive-on-spark
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
            - name: hive-on-spark
              mountPath: /opt/spark/conf/hive-site.xml
              subPath: hive-site.xml
            - name: hive-on-spark
              mountPath: /opt/spark/conf/spark-defaults.conf
              subPath: spark-defaults.conf
            - name: hive-on-spark
              mountPath: /opt/hive/conf/spark-defaults.conf
              subPath: spark-defaults.conf
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: hive-on-spark
          configMap:
            name: hive-on-spark
      restartPolicy: Always
      hostNetwork: true
      hostAliases:
        - ip: "192.168.199.56"
          hostnames:
            - "bigdata199056"
        - ip: "192.168.199.57"
          hostnames:
            - "bigdata199057"
        - ip: "192.168.199.58"
          hostnames:
            - "bigdata199058"
      nodeSelector:
        hiveserver2: "true"
      tolerations:
        - key: "bigdata"
          value: "true"
          operator: "Equal"
          effect: "NoSchedule"
